#!/usr/bin/env node
// Two helpers for voicing lines by hand in the ElevenLabs website.
//
//   node scripts/narration-sheet.mjs sheet
//     Writes narration-script/recording-sheet.md: every line in the game,
//     grouped by character, each with the exact filename to save it as.
//     Lines already recorded are checked off.
//
//   node scripts/narration-sheet.mjs manifest
//     Scans content/audio/narration/ for those files and rebuilds
//     manifest.json so the game plays whatever exists. Missing lines are
//     left as null and fall back to timed subtitles.
//
// Filenames follow <beatId>_<lineNumber>.mp3, matching generate-narration.mjs.

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const NARRATION_DIR = path.join(ROOT, "content", "audio", "narration");
const readJSON = async (rel) => JSON.parse(await readFile(path.join(ROOT, rel), "utf8"));

async function loadBeats() {
  const game = await readJSON("content/game.json");
  const beats = [];
  for (const chapter of game.chapters) {
    const data = await readJSON(`content/${chapter.file}`);
    for (const [id, beat] of Object.entries(data.beats || {})) {
      beat.lines.forEach((line, i) => {
        const file = `${id}_${i + 1}.mp3`;
        beats.push({ chapter: chapter.title, beatId: id, index: i, file, ...line });
      });
    }
  }
  return { game, lines: beats };
}

async function writeSheet() {
  const { game, lines } = await loadBeats();
  const bySpeaker = new Map();
  for (const l of lines) {
    if (!bySpeaker.has(l.speaker)) bySpeaker.set(l.speaker, []);
    bySpeaker.get(l.speaker).push(l);
  }
  const done = (l) => existsSync(path.join(NARRATION_DIR, l.file));
  const total = lines.length;
  const recorded = lines.filter(done).length;
  const chars = (ls) => ls.reduce((n, l) => n + l.text.length, 0);
  const out = [
    "# Recording sheet",
    "",
    "Generated by `node scripts/narration-sheet.mjs sheet`. Regenerate after script changes.",
    "",
    "Dashes are pauses for ElevenLabs: `-` short, `--` medium, `---` longer, `----` long. Paste each line exactly as shown. (Subtitles in the game use the clean text without dashes.)",
    "",
    "For each line: paste the text into ElevenLabs with that character's voice, download the mp3, and save it in `content/audio/narration/` with the filename shown. Then run `node scripts/narration-sheet.mjs manifest` so the game picks it up.",
    "",
    `**Progress:** ${recorded} of ${total} lines recorded.`,
    "",
    "| Character | Lines | Characters |",
    "|---|---|---|",
    ...[...bySpeaker].map(([s, ls]) => `| ${game.speakers[s] || s} | ${ls.length} | ${chars(ls)} |`),
    `| **Total** | **${total}** | **${chars(lines)}** |`,
    "",
  ];
  for (const [s, ls] of bySpeaker) {
    out.push(`## ${game.speakers[s] || s}`, "");
    let chapter = null;
    for (const l of ls) {
      if (l.chapter !== chapter) {
        chapter = l.chapter;
        out.push(`*${chapter}*`, "");
      }
      out.push(`- [${done(l) ? "x" : " "}] \`${l.file}\``, `  > ${l.spoken || l.text}`, "");
    }
  }
  const dest = path.join(ROOT, "narration-script", "recording-sheet.md");
  await writeFile(dest, out.join("\n"));
  console.log(`Wrote ${path.relative(ROOT, dest)}: ${recorded}/${total} lines recorded, ${chars(lines)} characters total.`);
}

async function writeManifest() {
  const { lines } = await loadBeats();
  const manifest = {};
  let found = 0;
  for (const l of lines) {
    if (!manifest[l.beatId]) manifest[l.beatId] = [];
    if (existsSync(path.join(NARRATION_DIR, l.file))) {
      manifest[l.beatId][l.index] = { speaker: l.speaker, file: l.file };
      found++;
    } else {
      manifest[l.beatId][l.index] = null;
    }
  }
  for (const key of Object.keys(manifest)) {
    if (manifest[key].every((x) => x === null)) delete manifest[key];
  }
  await writeFile(path.join(NARRATION_DIR, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  console.log(`manifest.json: ${found} of ${lines.length} lines have audio.`);
}

const cmd = process.argv[2];
if (cmd === "sheet") await writeSheet();
else if (cmd === "manifest") await writeManifest();
else {
  console.error("Usage: node scripts/narration-sheet.mjs sheet|manifest");
  process.exit(1);
}
